version: '3.8'
services:

  db-test:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-test
    command: -p 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - over

  backend-test:
    image: misieq/weii_ai_aplikacja_testujaca_backend
    restart: unless-stopped
    volumes:
      - ./backend/src/:/app/
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
      - BACKEND_URL=http://backend:8000
      - BACKEND_USER=admin
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5673
      - BACKEND_PASSWORD=admin
      - LC_TIME="pl_PL"
      - USE_POSTGRES=TRUE
    command: sh -c '(./wait-for db-test:5433 -- ./db-ops.sh ) &&  python3 ./manage.py runserver 0.0.0.0:8002'
    ports: 
      - 8002:8002
    depends_on:
      - rabbitmq
    networks:
      - over


  frontend-test:
    image: misieq/weii_ai_aplikacja_testujaca_frontend
    restart: unless-stopped
    environment:
      - LC_TIME="pl_PL"
    ports:
      - 8082:8080
    depends_on:
      - backend-test
    networks:
      - over  

  celery:
    image: misieq/weii_ai_aplikacja_testujaca_backend
    command: celery -A api_client  worker -l info
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5673
      - BACKEND_URL=http://backend:8000      
      - BACKEND_USER=admin
      - BACKEND_PASSWORD=admin
      - LC_TIME="pl_PL"
      - USE_POSTGRES=TRUE
    volumes:
      - ./backend/src/:/app/
    depends_on:
      - frontend-test
    networks:
      - over


  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5673
        - RABBITMQ_DEFAULT_PASS=guest
        - LC_TIME="pl_PL"
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
        - "15673:15672"  
        - "5673:5673"
    networks:
      - over

networks:
  over:
    external: true

volumes:
  pgdata:
